name: Label Issue by Priority

on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v4

    - name: Add Label Issue Content
      id: add_label
      run: |
        node -e "
          const core = require('@actions/core');
          const issueBody = process.env.ISSUE_BODY;
          let label = '';

          if (issueBody.includes('### 緊急度\n\n緊急')) {
            label = '緊急';
          } else if (issueBody.includes('### 緊急度\n\n高')) {
            label = '優先度: 高';
          } else if (issueBody.includes('### 緊急度\n\n中')) {
            label = '優先度: 中';
          } else if (issueBody.includes('### 緊急度\n\n低')) {
            label = '優先度: 低';
          }

          if (label) {
            core.setOutput('label', label);
          }
        "
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}

    - name: Apply label
      if: steps.add_label.outputs.label != ''
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: ${{ steps.add_label.outputs.label }}
