name: Update Issue Labels

on:
  issues:
    types: [edited]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check Issue Body for Labels
        uses: actions/github-script@v6
        with:
          script: |
            const issue = github.context.payload.issue;
            const body = issue.body || '';
            
            const priorityMatch = body.match(/### (緊急度|優先度)\s*(緊急|高|中|低)/);
            if (!priorityMatch) {
              return;
            }
            
            const urgency = priorityMatch[1];
            const labelMap = {
              '緊急': '緊急',
              '高': '優先度: 高',
              '中': '優先度: 中',
              '低': '優先度: 低'
            };

            const currentLabels = issue.labels.map(label => label.name);
            const newLabel = labelMap[urgency];
            
            // remove
            const priorityLabels = ['緊急', '優先度: 高', '優先度: 中', '優先度: 低'];
            const labelsToRemove = currentLabels.filter(label => priorityLabels.includes(label));

            // add
            const labelsToAdd = currentLabels.filter(label => !priorityLabels.includes(label));
            if (!currentLabels.includes(newLabel)) {
              labelsToAdd.push(newLabel);
            }

            // update
            await github.rest.issues.setLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: labelsToAdd
            });

            console.log(`Updated labels: ${labelsToAdd.join(', ')}`);
