name: Update Issue Labels

on:
  issues:
    types: [edited]

jobs:
  update-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Determine labels
        id: determine_labels
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || '';
            
            // Define the regex to extract the priority
            const priorityMatch = body.match(/### (緊急度|優先度)\s*\n\s*(緊急|高|中|低)/);
            
            if (!priorityMatch) {
              console.log('no edit because not match.');
              return { newLabel: '', labelsToRemove: [] };
            }
            
            const urgency = priorityMatch[2];
            const labelMap = {
              '緊急': '緊急',
              '高': '優先度: 高',
              '中': '優先度: 中',
              '低': '優先度: 低'
            };

            const currentLabels = issue.labels.map(label => label.name);
            const newLabel = labelMap[urgency];
            const priorityLabels = ['緊急', '優先度: 高', '優先度: 中', '優先度: 低'];
            const labelsToRemove = currentLabels.filter(label => priorityLabels.includes(label) && label !== newLabel);
            
            return JSON.stringify({ newLabel, labelsToRemove });
          result-encoding: string

      - name: Update labels
        if: steps.determine_labels.outputs.result != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
        run: |
          result='${{ steps.determine_labels.outputs.result }}'
          new_label=$(echo "$result" | jq -r '.newLabel')
          labels_to_remove=$(echo "$result" | jq -r '.labelsToRemove | join(" ")')

          # remove labels
          echo "$labels_to_remove"
          for label in $labels_to_remove; do
            echo "removing label: $label"
            gh issue edit $issue_number --remove-label "$label"
          done

          # add new label
          if [ -n "$new_label" ]; then
            echo "adding label: $new_label"
            gh issue edit "$NUMBER" --add-label "$new_label"
          fi
          
