name: Update Issue Labels

on:
  issues:
    types: [edited]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Determine labels
        id: determine_labels
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || '';
            
            // Define the regex to extract the priority
            const priorityMatch = body.match(/### (緊急度|優先度)\s*\n\s*(緊急|高|中|低)/);
            
            if (!priorityMatch) {
              console.log('no edit because not match.');
              return { newLabel: '', labelsToRemove: [] };
            }
            
            const urgency = priorityMatch[2];
            const labelMap = {
              '緊急': '緊急',
              '高': '優先度: 高',
              '中': '優先度: 中',
              '低': '優先度: 低'
            };

            const currentLabels = issue.labels.map(label => label.name);
            const newLabel = labelMap[urgency];
            const priorityLabels = ['緊急', '優先度: 高', '優先度: 中', '優先度: 低'];
            const labelsToRemove = currentLabels.filter(label => priorityLabels.includes(label) && label !== newLabel);
            
            return { newLabel, labelsToRemove };
          result-encoding: string

      - name: Update labels
        if: steps.determine_labels.outputs.result != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          labels_to_remove="${{ steps.determine_labels.outputs.result[0] }}"
          new_label="${{ steps.determine_labels.outputs.result[1] }}"
          issue_number="${{ github.event.issue.number }}"

          echo "${{ steps.determine_labels.outputs.result }}"
          echo "Labels to remove: $labels_to_remove"
          echo "New label to add: $new_label"
          echo "Issue number: $issue_number"

          # remove label
          for label in ${labels_to_remove[@]}; do
            gh issue edit $issue_number --remove-label "$label"
          done

          # add label
          gh issue edit $issue_number --add-label "$new_label"

